server:
  port: 6061
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      order_inserts: true
      order_updates: true
      jdbc:
        batch_size: 50
        batch_versioned_data: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    listener:
      missing-topics-fatal: false
      ack-mode: RECORD
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: order_store_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        allow.auto.create.topics: true
        spring.json.trusted.packages: "*"
        spring.json.type.mapping:
          orderCanceledEventDTO:com.fawry.order_api.domain.event.OrderCanceledEventDTO

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping:
          orderCreatedEventDTO:com.fawry.order_api.domain.event.OrderCreatedEventDTO,
          orderCancelNotificationEvent:com.fawry.order_api.domain.event.OrderCancelNotificationEvent

        acks: all
        retries: 3
  redis:
    host: localhost
    port: 6381
redis:
  job:
   queue:
     name: order-create-queue
custom:
  order:
    topic:
      name: order-events
      total_partitions: 5
configuration:
  kafka:
    scheduled: 5000
    outbox-topic: outbox-topic
resilience4j:
  circuitbreaker:
    instances:
      couponService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
  retry:
    instances:
      couponService:
        maxRetryAttempts: 3
        waitDuration: 500
        enableRandomizedWait: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    metrics:
      enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha